default_agent: CustomerSupport
agents:
  CustomerSupport:
    name: CustomerSupport
    language: python
    node_version: '20'
    entrypoint: /voc/work/Project_starter/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /voc/work/Project_starter
    aws:
      execution_role: arn:aws:iam::220422419370:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-8174cc8956
      execution_role_auto_create: false
      account: '220422419370'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-220422419370-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: CustomerSupport-0lJdjG24IT
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:220422419370:runtime/CustomerSupport-0lJdjG24IT
      agent_session_id: ec72a847-e578-4969-9e57-4694f3296305
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: CustomerSupportMemory-DB1PUR74Zh
      memory_arn: null
      memory_name: CustomerSupport_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
